import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — BoostCart',
  description: 'BoostCart privacy policy. Learn how we handle your data.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-gray-500 mb-10">Last updated: June 28, 2025</p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Who We Are</h2>
            <p className="text-gray-700 leading-relaxed">
              BoostCart is a post-purchase upsell application for BigCommerce, operated by Jon Guidroz.
              If you have questions about this policy, contact us at{' '}
              <a href="mailto:support@boostcart.io" className="text-blue-600 hover:underline">
                support@boostcart.io
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">What Data We Collect</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              When you install BoostCart, we access the following data through the BigCommerce API:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-1">
              <li><strong>Store information</strong> — Store name, domain, and configuration</li>
              <li><strong>Product data</strong> — Product names, prices, images, and categories</li>
              <li><strong>Order data</strong> — Order totals, items purchased, and customer group info</li>
              <li><strong>Analytics events</strong> — Upsell impressions, clicks, and conversions generated by BoostCart</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">What We Don&apos;t Collect</h2>
            <p className="text-gray-700 leading-relaxed">
              We <strong>do not</strong> collect or store credit card numbers, payment credentials, or any
              raw payment data. All payment processing is handled entirely by BigCommerce and your
              chosen payment gateway. We never see or touch that information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">How We Store Data</h2>
            <p className="text-gray-700 leading-relaxed">
              Your data is stored in a PostgreSQL database hosted on Neon.tech in the US East region.
              All connections are encrypted in transit (TLS) and data is encrypted at rest. We retain
              your data only for as long as your BoostCart account is active.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">How We Use Your Data</h2>
            <ul className="list-disc pl-6 text-gray-700 space-y-1">
              <li>To display and manage your upsell offers</li>
              <li>To track upsell performance (impressions, clicks, revenue)</li>
              <li>To improve the BoostCart service</li>
              <li>To communicate with you about your account</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-3">
              We do not sell your data to third parties. Ever.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Third-Party Services</h2>
            <p className="text-gray-700 leading-relaxed">
              We use the following services to operate BoostCart:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-1">
              <li><strong>BigCommerce</strong> — Platform API for store data</li>
              <li><strong>Neon.tech</strong> — Database hosting</li>
              <li><strong>Vercel</strong> — Application hosting</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Your Rights (GDPR &amp; CCPA)</h2>
            <p className="text-gray-700 leading-relaxed">
              You have the right to:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-1">
              <li><strong>Access</strong> your data — request a copy of what we store</li>
              <li><strong>Correct</strong> inaccurate data</li>
              <li><strong>Delete</strong> your data — we&apos;ll remove it upon request</li>
              <li><strong>Export</strong> your data in a portable format</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-3">
              To exercise any of these rights, email{' '}
              <a href="mailto:support@boostcart.io" className="text-blue-600 hover:underline">
                support@boostcart.io
              </a>{' '}
              and we&apos;ll respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Data Retention</h2>
            <p className="text-gray-700 leading-relaxed">
              We retain your data while your BoostCart account is active. If you uninstall the app,
              we&apos;ll delete your data within 30 days. You can also request immediate deletion at any time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Changes to This Policy</h2>
            <p className="text-gray-700 leading-relaxed">
              We may update this policy from time to time. We&apos;ll notify you of significant changes
              via email or an in-app notice. Continued use of BoostCart after changes constitutes
              acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">Contact</h2>
            <p className="text-gray-700 leading-relaxed">
              Questions? Reach us at{' '}
              <a href="mailto:support@boostcart.io" className="text-blue-600 hover:underline">
                support@boostcart.io
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
